fix a bunch of os-specific bugs

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,30 +1,72 @@
 #!/bin/bash
+set -euxo pipefail
 
 # Check for salt-call and move on if it exists.
 if [[ $(which salt-call &>/dev/null; echo $?) -ne 0 ]]; then
     if cat /etc/lsb-release 2>&1 | grep -q Ubuntu; then
+        # Ensure sudo exists.
+        if [[ $(which sudo &>/dev/null; echo $?) -ne 0 ]]; then
+            apt-get update
+            apt-get install -y sudo
+        fi
+
+        # Ensure core utilities exist.
+        sudo apt-get update
+        sudo apt-get install -y \
+            curl \
+            git \
+            gnupg \
+            wget
+
         version=$(cat /etc/lsb-release | grep RELEASE | cut -d"=" -f2)
         codename=$(cat /etc/lsb-release | grep CODENAME | cut -d"=" -f2)
         if [[ "${version}" == "14.04" ]]; then
+            # https://unix.stackexchange.com/a/362157
+            sudo mkdir /dev/fuse
+            sudo chmod 777 /dev/fuse
+
             # The version in the apt repos is from 2014, so we sudo pip install.
             # YOLO!
-            sudo pip install salt
+            sudo apt-get update
+            sudo apt-get install -y \
+                python3-apt \
+                python3-dev \
+                python3-gdbm \
+                python3-pip \
+                python3-tk
+            sudo pip3 install --upgrade setuptools
+            sudo pip3 install --upgrade pip
+            sudo pip3 install --upgrade --ignore-installed six
+            sudo pip3 install salt
         else
             wget -O - "https://repo.saltstack.com/py3/ubuntu/${version}/amd64/latest/SALTSTACK-GPG-KEY.pub" | sudo apt-key add -
             sudo bash -c "echo deb http://repo.saltstack.com/py3/ubuntu/${version}/amd64/latest ${codename} main > /etc/apt/sources.list.d/saltstack.list"
             sudo apt-get update
-            sudo apt-get install salt-minion -y
+            sudo /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get install -y salt-minion"
         fi
     elif cat /etc/issue 2>&1 | grep -E "(Arch|Manjaro)" -q; then
-        sudo pacman --needed -Syu community/salt
+        sudo pacman --noconfirm --needed -Syu community/salt lsb-release
     elif [[ $(uname) == Darwin ]]; then
         brew install saltstack
     fi
 fi
 
 # Update the repository.
-git pull
+set +ue
+if [[ "${CI}" != true ]]; then
+    git pull
+fi
+set -ue
+
+# Set a custom OS grain for Manjaro.
+if cat /etc/lsb-release | grep Manjaro; then
+    sudo bash -c "echo os: Arch > /etc/salt/grains"
+fi
 
 # Run salt.
 # add "-l debug" to the salt-call command to produce verbose output
-sudo bash -c "export HOME=${HOME}; salt-call --local --file-root=./salt --state-output=mixed --force-color --log-level=info state.apply 2>&1" | grep --color=never -v stty
+sudo bash -c "export HOME=${HOME}; salt-call --local --file-root=./salt --state-output=mixed -l info --force-color --out-file=/tmp/salt-call.log state.apply 2>&1"
+cat /tmp/salt-call.log | grep --color=never -v stty
+
+# Exit with non-zero status if a failure occurred.
+cat /tmp/salt-call.log | grep Failed | sed -E "s/[[:space:]]+/ /g" | grep -q ": 0" || exit 1
